
---
- hosts: debian
  remote_user: bastion
  become: true
  tasks:
  - name: test connectivity
    command: hostname
  - name: copy openmediavault repo  
    shell: |
      cat <<EOF >> /etc/apt/sources.list.d/openmediavault.list
      deb https://packages.openmediavault.org/public shaitan main
      # deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] https://downloads.sourceforge.net/project/openmediavault/packages shaitan main
      ## Uncomment the following line to add software from the proposed repository.
      # deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] https://packages.openmediavault.org/public shaitan-proposed main
      # deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] https://downloads.sourceforge.net/project/openmediavault/packages shaitan-proposed main
      ## This software is not part of OpenMediaVault, but is offered by third-party
      ## developers as a service to OpenMediaVault users.
      # deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] https://packages.openmediavault.org/public shaitan partner
      # deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] https://downloads.sourceforge.net/project/openmediavault/packages shaitan partner
      EOF
  - name: install openmediavault
    shell: |
      apt-get install --yes gnupg
      wget -O "/etc/apt/trusted.gpg.d/openmediavault-archive-keyring.asc" https://packages.openmediavault.org/public/archive.key
      apt-key add "/etc/apt/trusted.gpg.d/openmediavault-archive-keyring.asc"
      export LANG=C.UTF-8
      export DEBIAN_FRONTEND=noninteractive
      export APT_LISTCHANGES_FRONTEND=none
      apt-get update -y
      apt-get --yes --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends --option DPkg::Options::="--force-confdef" --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault
  - name: populate database
    shell: |
      omv-confdbadm populate
  - name: deploy host 
    shell: |
      omv-salt deploy run hosts