- hosts: 127.0.0.1
  connection: local
  become: true
- name: update ssh_config with proxy jump
  hosts: 127.0.0.1
  tags: [ 'proxy_jump' ]
  tasks:
    - name: update ssh_conf for network 10.10.*
      run_once: true
      become: true
      shell: |
        tee -a /etc/ssh/ssh_config << END
        Host 10.10.*
          Port 22
          User bastion
          KexAlgorithms curve25519-sha256,ecdh-sha2-nistp521
          IdentityFile ../ssh_keys/idrsa
          ProxyCommand ssh -i ../ssh_keys/idrsa  bastion@{{ item }} -W %h:%p
        END
      with_items: "{{hostvars[inventory_hostname].groups.bastion[0]}}"