
---
- hosts: bastion
  remote_user: bastion
  become: true
  tags: setup
  tasks:
  - name: ensure private key and public one are present
    copy: 
      src: "../../../ssh_keys/{{ item }}"
      dest: "/home/bastion/.ssh/{{ item }}" 
      mode: 0700
    with_items:
      - idrsa.pub
      - idrsa

  - name: change ssh_kyes ownership to bastion
    command: chown -R bastion:bastion /home/bastion/.ssh/

  - name: add ssh agent 
    shell: |
      eval "$(ssh-agent)"
      ssh-add /home/bastion/.ssh/idrsa     