
---
- hosts: bastion
  remote_user: bastion
  become: true
  tasks:
  - name: ensure private key and public one are present
    copy: 
      src: "../../../ssh_keys/{{ item }}"
      dest: "/home/bastion/.ssh/{{ item }}" 
      mode: 0700
    with_items:
      - idrsa.pub
      - idrsa

  - name: change ssh_kyes ownership to bastion
    command: chown -R bastion:bastion /home/bastion/.ssh/

  - name: add ssh agent 
    shell: |
      eval "$(ssh-agent)"
      ssh-add /home/bastion/.ssh/idrsa     
       
- hosts: 127.0.0.1
  connection: local
  become: true
- name: update ssh_config with proxy jump
  hosts: 127.0.0.1
  tasks:
    - name: update ssh_conf for network 10.10.*
      shell: |
        tee -a /etc/ssh/ssh_config << END
        Host 10.10.*
          Port 22
          User bastion
          KexAlgorithms curve25519-sha256,ecdh-sha2-nistp521
          IdentityFile ../ssh_keys/idrsa
          ProxyCommand ssh -i ../ssh_keys/idrsa  bastion@{{ item }} -W %h:%p
        END
      with_items: "{{hostvars[inventory_hostname].groups.bastion[0]}}"