- name: create RBD pool
  shell: |
    ceph osd pool create rbd 64
    ceph mgr module enable pg_autoscaler
    ceph osd pool set rbd pg_autoscale_mode on
    rbd pool init rbd
    ceph osd pool autoscale-status
    rbd create --size 5G --pool rbd rbd01
    rbd ls -l
  tags: ceph_client

- name: map block device
  shell: |
    rbd map rbd01
    rbd showmapped
  tags: ceph_client

- name: list volumes
  shell: rbd ls -l
  tags: ceph_client

- name: format with XFS
  shell: mkfs.xfs /dev/rbd0
  tags: ceph_client

- name: mount volume
  shell: mount /dev/rbd0 /mnt
  tags: ceph_client

- name: check volumes
  shell: df -hT
  tags: ceph_client