- name: setup monitor deamon
  tags: ['ceph_monitor']
  shell: |
    mkdir /var/lib/ceph/mon/ceph-{{ item }}
    ceph-mon --cluster ceph --mkfs -i {{ item }} --monmap /etc/ceph/monmap --keyring /etc/ceph/ceph.mon.keyring
    chown ceph. /etc/ceph/ceph.*
    chown -R ceph. /var/lib/ceph/mon/ceph-{{ item }} /var/lib/ceph/bootstrap-osd
  with_items: "{{ hostvars[inventory_hostname].name }}"
- name: enable and start monitor service
  tags: ['ceph_monitor']
  shell: |
    systemctl enable --now ceph-mon@{{ item }}
    systemctl start ceph-mon@{{ item }}
  with_items: "{{ hostvars[inventory_hostname].name }}"
- name: enable monitor protocol
  tags: ['ceph_monitor']
  shell: |
    ceph mon enable-msgr2
    ceph config set mon auth_allow_insecure_global_id_reclaim false