- name: create volume from disk
  tags: ceph_osd
  shell: |
    parted --script /dev/sdb 'mklabel gpt';
    parted --script /dev/sdb "mkpart primary 0% 100%";
    ceph-volume lvm create --data /dev/sdb1