- hosts: 127.0.0.1
  connection: local
  become: true
  vars_files:
      - ../../ceph_cluster_configuration.yml
  tasks:
      - name: Remove block of text
        tags: destroy
        ansible.builtin.blockinfile:
          path: /etc/ssh/ssh_config
          state: absent
          marker: "# {mark} proxy jump ceph cluster"

      - name: Insert a block at the beginning of a file
        tags: apply
        ansible.builtin.blockinfile:
          path: /etc/ssh/ssh_config
          insertafter: BOF
          block: |
            Host {{ item }}
              Port 22
              User {{username}}
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
              KexAlgorithms curve25519-sha256,ecdh-sha2-nistp521
            Host 10.10.*
              Port 22
              User {{username}}
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
              KexAlgorithms curve25519-sha256,ecdh-sha2-nistp521
              IdentityFile ../ssh_keys/idrsa
              ProxyCommand ssh -o StrictHostKeychecking=no -i ../ssh_keys/idrsa  {{username}}@{{ item }} -W %h:%p
          marker: "# {mark} proxy jump ceph cluster"
        with_items: "{{hostvars[inventory_hostname].groups.bastion[0]}}"