---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../ceph_cluster_configuration.yml
  tasks:
    - include_tasks: ../playbooks/init/build_inventory.yaml
    - include_tasks: ../playbooks/init/build_tfvars.yaml
    - include_tasks: ../playbooks/init/tf_state.yaml