- hosts: manager
  remote_user: bastion
  become: true
  vars_files:
    - ../ceph_cluster_configuration.yml
  tasks:
    - include_tasks: ../playbooks/ceph_monitor.yaml
    - include_tasks: ../playbooks/ceph_manager.yaml