- name: check if local pub ip is inside of ip's list
  register: pub_ip
  command: curl ifconfig.me

- name: append local pub ip into allow list 
  when:  item not in allow_ip_list
  set_fact:
    allow_ip_list: "{{ allow_ip_list + [ item ] }}"
  with_items: "{{ pub_ip.stdout }}/32"
  
- name: write vars into tfvars file
  shell: |
    echo "" > ../../terraform/env.tfvars
    tee -a ../../terraform/env.tfvars << EOF
    tfstate_bucket_name="{{ bucket_name }}"
    project_name="{{ project_name }}"
    project_id="{{ project_id }}"
    region="{{ region }}"
    ip_isp_pub={{ allow_ip_list | replace("'",'"') }}
    path_local_public_key="{{ path_local_public_key }}"
    username="{{username}}"
    image="{{image}}"
    scopes={{scopes | replace("'",'"') }}
    
    osd_nodes_number={{hosts.osd.node_numbers}}
    osd_volumes={{ hosts.osd.volumes_per_instance * hosts.osd.node_numbers |int }}
    osd_volumes_per_instance={{hosts.osd.volumes_per_instance}}
    osd_volume_sizes_gb={{hosts.osd.volume_sizes_gb}}
    osd_volume_type="{{hosts.osd.volume_type}}"
    osd_machine_type="{{hosts.osd.machine_type}}"
    osd_provisioning_model="{{hosts.osd.provisioning_model}}"
    osd_tags={{hosts.osd.tags| replace("'",'"') }}
    
    rdb_nodes_number={{hosts.rdb.node_numbers}}
    rdb_machine_type="{{hosts.rdb.machine_type}}"
    rdb_provisioning_model="{{hosts.rdb.provisioning_model}}"
    rdb_tags={{hosts.rdb.tags| replace("'",'"') }}

    monitor_nodes_number={{hosts.monitor.node_numbers}}
    monitor_machine_type="{{hosts.monitor.machine_type}}"
    monitor_provisioning_model="{{hosts.monitor.provisioning_model}}"
    monitor_tags={{hosts.monitor.tags| replace("'",'"') }}

    manager_nodes_number={{hosts.manager.node_numbers}}
    manager_machine_type="{{hosts.manager.machine_type}}"
    manager_provisioning_model="{{hosts.manager.provisioning_model}}"
    manager_tags={{hosts.manager.tags| replace("'",'"') }}

    bastion_machine_type="{{hosts.bastion.machine_type}}"
    bastion_provisioning_model="{{hosts.bastion.provisioning_model}}"
    bastion_tags={{hosts.bastion.tags| replace("'",'"') }}
    EOF
