---
- hosts: 127.0.0.1
  connection: local
- name: build tfvars localy
  hosts: 127.0.0.1
  vars_files:
    - ../../variables/var.yml
  tags: [ 'apply', init ]
  tasks:
    - name: check if local pub ip is inside of ip's list
      register: pub_ip
      command: curl ifconfig.me
    
    - name: append local pub ip into allow list 
      when:  item  not in allow_ip_list
      set_fact:
        allow_ip_list: "{{ allow_ip_list + [ item ] }}"
      with_items: "{{ pub_ip.stdout }}/32"
      
    - name: write vars into tfvars file
      shell: |
        echo "" > ../../../terraform/env_test.tfvars
        tee -a ../../../terraform/env_test.tfvars << EOF
        tfstate_bucket_name="{{ bucket_name }}"
        project_name="{{ project_name }}"
        project_id="{{ project_id }}"
        region="{{ region }}"
        ip_isp_pub={{ allow_ip_list | replace("'",'"') }}
        path_local_public_key="{{ path_local_public_key }}"
        EOF

